image: markformware/gitpod-workspace-qemu:latest

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore

tasks:
  - name: zig build run
    init:
      mv tools/zig/lib/std/zig aside-zig
      && ./tools/update-tools.sh
      && diff -r baseline/tools/zig/lib/std/zig tools/zig/lib/std/zig
      && rm -rf tools/zig/lib/std/zig
      && mv aside-zig tools/zig/lib/std/zig
    command:
      export PATH=./tools/zig:$PATH
      && echo building ...
      && zig build run