image: markformware/gitpod-workspace-qemu:latest

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore

tasks:
  - name: zig build run
    init: ./tools/update-tools.sh
    command:
      export PATH=./tools/zig:$PATH
      && echo building ...
      && zig build run