image: markformware/gitpod-workspace-qemu:latest

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser

tasks:
  - name: zig build run
    init: ./tools/update-tools.sh
    command:
      export PATH=./tools/zig:$PATH
      && echo building ...
      && zig build run

vscode:
  extensions:
    - augusterame.zls-vscode@1.0.4:ZQxqRwcEt9rZuan0J+3BRQ==
    - tiehuis.zig@0.2.5:Yj8BTORJw/zERdoSGPf+eQ==
    - lorenzopirro.zig-snippets@2.1.0:yjJl88xYcmvLdSifCQMz7g==